import { FileText, Download, CheckCircle2, Calendar, Clock, ShieldOff } from "lucide-react"

const MOCK_REPORTS = [
  {
    id: "REP-2026-089",
    title: "Operation Nexus: Hawala Financial Channel Disruption",
    date: "Sep 08, 2026",
    classification: "TOP SECRET // LE ONLY",
    summary: "Complete financial flow tracing revealing 14 shell accounts linked to primary kingpin P042 and mule phone +91-9876543210. Cross-border remittances identified across UAE, Dubai and Hong Kong corridors.",
    risk: "CRITICAL",
    entitiesInvolved: 24,
    status: "Finalized",
  },
  {
    id: "REP-2026-084",
    title: "Syndicate Logistics & Cross-Border Vehicle Movement",
    date: "Sep 05, 2026",
    classification: "CONFIDENTIAL",
    summary: "Automated toll tag and ANPR tracking correlating suspect vehicles DL 3C AB 4821 with warehouse locations in Sector 18 Gurgaon. 3 additional vehicles identified as part of the fleet.",
    risk: "HIGH",
    entitiesInvolved: 11,
    status: "Under Review",
  },
  {
    id: "REP-2026-077",
    title: "Corporate Front Entities MCA Registry Audit",
    date: "Aug 29, 2026",
    classification: "INTERNAL USE",
    summary: "Directorship mapping connecting Global Exports Ltd to multiple unlisted shell corporations sharing identical registered office addresses in Mumbai and Pune.",
    risk: "MEDIUM",
    entitiesInvolved: 8,
    status: "Actioned",
  },
  {
    id: "REP-2026-071",
    title: "Dark Web Narcotics Procurement Network — Operation Cobra",
    date: "Aug 22, 2026",
    classification: "TOP SECRET // LE ONLY",
    summary: "Cryptocurrency tracing (Monero/BTC) linked to 6 dark-web vendor accounts operating out of Bengaluru and Hyderabad. Physical handoff nodes identified at 3 courier aggregators.",
    risk: "CRITICAL",
    entitiesInvolved: 19,
    status: "Active Investigation",
  },
  {
    id: "REP-2026-065",
    title: "Cyber Fraud Call-Centre Syndicate — Phase II Mapping",
    date: "Aug 14, 2026",
    classification: "CONFIDENTIAL",
    summary: "VoIP infrastructure analysis revealing 4 interconnected call centres defrauding NRI victims across UK and Canada. Mule account network spans 37 accounts across 9 banks.",
    risk: "HIGH",
    entitiesInvolved: 42,
    status: "Under Review",
  },
  {
    id: "REP-2026-058",
    title: "Human Trafficking Pipeline — Nepal–Delhi–Gulf Corridor",
    date: "Aug 06, 2026",
    classification: "RESTRICTED",
    summary: "Victim recruitment pattern analysis covering 18 origination districts. Broker network identified with 7 primary nodes and 22 secondary facilitators using social media recruitment.",
    risk: "CRITICAL",
    entitiesInvolved: 31,
    status: "Finalized",
  },
  {
    id: "REP-2026-049",
    title: "Illicit Arms Cache — Punjab Border District Analysis",
    date: "Jul 28, 2026",
    classification: "TOP SECRET",
    summary: "Geo-spatial clustering of seizure data suggests 3 active smuggling corridors. Drone-drop incidents correlated with 2 suspect phone clusters near Amritsar and Tarn Taran.",
    risk: "CRITICAL",
    entitiesInvolved: 15,
    status: "Actioned",
  },
  {
    id: "REP-2026-041",
    title: "Real-Estate Money Laundering — Tier-2 City Benami Holdings",
    date: "Jul 19, 2026",
    classification: "INTERNAL USE",
    summary: "Property registration data cross-referenced with IT returns flagging 63 benami transactions in Indore, Nagpur, and Lucknow. Estimated laundered value: Rs. 148 crore.",
    risk: "HIGH",
    entitiesInvolved: 27,
    status: "Under Review",
  },
]

const RISK_STYLES: Record<string, string> = {
  CRITICAL: "bg-rose-500/10 border border-rose-500/30 text-rose-400",
  HIGH:     "bg-amber-500/10 border border-amber-500/30 text-amber-400",
  MEDIUM:   "bg-teal-500/10 border border-teal-500/30 text-teal-400",
  LOW:      "bg-slate-500/10 border border-slate-500/30 text-slate-400",
}

type Report = (typeof MOCK_REPORTS)[number]

function buildPdfStream(lines: string[]): string {
  const ops: string[] = ["BT", "/F1 11 Tf", "50 740 Td", "14 TL"]
  for (const line of lines) {
    const safe = line.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)")
    ops.push(`(${safe}) Tj T*`)
  }
  ops.push("ET")
  return ops.join("\n")
}

function downloadReportPDF(report: Report) {
  const lines = [
    "CRIMINAL NETWORK ANALYSIS SYSTEM",
    `Intelligence Report  ${report.id}`,
    "",
    `Classification : ${report.classification}`,
    `Risk Level     : ${report.risk} THREAT`,
    `Date           : ${report.date}`,
    `Status         : ${report.status}`,
    `Entities       : ${report.entitiesInvolved} nodes`,
    "",
    "Title:",
    report.title,
    "",
    "Executive Summary:",
    ...report.summary.match(/.{1,90}/g) ?? [report.summary],
    "",
    "--- This document is generated by CNAS and is classified " + report.classification + ". ---",
    "--- Unauthorised disclosure is prohibited under the Official Secrets Act. ---",
  ]

  const stream = buildPdfStream(lines)
  const streamLen = new TextEncoder().encode(stream).length

  const pdf = [
    "%PDF-1.4",
    "1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj",
    "2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj",
    "3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj",
    `4 0 obj<</Length ${streamLen}>>`,
    "stream",
    stream,
    "endstream",
    "endobj",
    "5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Courier>>endobj",
    "xref",
    "0 6",
    "0000000000 65535 f\r",
    "trailer<</Size 6/Root 1 0 R>>",
    "startxref",
    "9",
    "%%EOF",
  ].join("\n")

  const blob = new Blob([pdf], { type: "application/pdf" })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement("a")
  a.href     = url
  a.download = `${report.id}.pdf`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

const StatusIcon: Record<string, JSX.Element> = {
  Finalized:              <CheckCircle2 size={13} className="text-emerald-400" />,
  "Under Review":         <Clock        size={13} className="text-amber-400"   />,
  Actioned:               <CheckCircle2 size={13} className="text-teal-400"    />,
  "Active Investigation": <ShieldOff    size={13} className="text-rose-400"    />,
}

function Reports() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="page-title">Intelligence Reports &amp; Briefings</h2>
          <p className="mt-1 text-sm muted-text">
            Official synthesized investigation briefings, threat scores, and evidence dossiers
          </p>
        </div>

        <button className="inline-flex items-center gap-2 rounded-xl border border-teal-500/30 bg-teal-500/10 px-4 py-2 text-sm font-semibold text-teal-300 hover:bg-teal-500/20 transition">
          <FileText size={16} />
          <span>Generate New Dossier</span>
        </button>
      </div>

      <div className="grid gap-4">
        {MOCK_REPORTS.map((report) => (
          <div key={report.id} className="app-surface p-6 transition hover:border-slate-700">
            <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start">
              <div>
                <div className="flex flex-wrap items-center gap-3">
                  <span className="rounded-md border border-slate-700 bg-slate-800 px-2.5 py-0.5 text-xs font-mono font-semibold text-slate-300">
                    {report.id}
                  </span>
                  <span className={`rounded-md px-2.5 py-0.5 text-xs font-bold ${RISK_STYLES[report.risk] ?? RISK_STYLES.LOW}`}>
                    {report.risk} THREAT
                  </span>
                  <span className="text-xs font-medium text-slate-500">{report.classification}</span>
                </div>

                <h3 className="mt-2.5 text-base font-semibold text-white">{report.title}</h3>
                <p className="mt-1.5 text-sm text-slate-400 max-w-3xl">{report.summary}</p>
              </div>

              <div className="flex shrink-0 items-center gap-2">
                <button
                  onClick={() => downloadReportPDF(report)}
                  className="inline-flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800/90 px-3 py-2 text-xs font-medium text-slate-200 hover:bg-slate-700 transition"
                >
                  <Download size={14} />
                  <span>Download PDF</span>
                </button>
              </div>
            </div>

            <div className="mt-5 flex flex-wrap items-center gap-6 border-t border-slate-800/80 pt-3 text-xs text-slate-500">
              <span className="flex items-center gap-1.5">
                <Calendar size={13} className="text-slate-400" />
                {report.date}
              </span>
              <span>
                Entities Analyzed:{" "}
                <span className="font-semibold text-slate-300">{report.entitiesInvolved} nodes</span>
              </span>
              <span className="flex items-center gap-1.5">
                {StatusIcon[report.status] ?? <CheckCircle2 size={13} className="text-slate-400" />}
                Status: {report.status}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default Reports
